### ISSUE TITLE
Absence records are displaying on maps which is misleading

### ISSUE THREAD

**Issue by EllaVogel** [nbnuk/nbnatlas-issues#237]
E.g. records of pacific oyster are showing to have a wider distribution than they do, as absence records are marked on maps in the same way as presence records. Can we have absence records showing with a different symbol instead?

**Comment by MandyHenshall** [comment]
We have also had an email about this from MBA - "‘Absence’ records showing as present, for example Didemnum vexillum and about another 35 marine species that we regularly record absences for during our marina surveys. It isn’t just on the maps, the downloaded records are also shown as Presences". 
They have asked if we can give a timescale for when it will be fixed, and possibly put a warning message on the website.

**Comment by GiselleSterry** [comment]
See also - https://github.com/nbnuk/nbnatlas-issues/issues/215

**Comment by djtfmartin** [comment]
this is now fixed.

**Comment by MandyHenshall** [comment]
I let the MBA know and they have come back with the following:
I have had a quick look at a few species, Didemnum vexillum and Undaria pinnatifida, and have the following comments to make:
1)	The detail maps are now showing only presence records and the downloaded records include the word ‘Absent’ for absence records
2)	However, the number of occurrences is still showing the number of presence + absence records which I think will be very confusing for users, either this should be reworded to number of presences & absences, or the number changed to only include presence records.
•  species: Didemnum vexillum Kott, 2002 
Didemnum vexillum Kott, 2002
Didemnum vexillum
Occurrences: 144 
3)	The initial map of occurrences is still showing presences + absences, again either the wording should be changed or only presence records shown
4)	The absences are not displayed on the detail map, NBNGateway used to show these in a different colour and you could choose to display them.

**Comment by djtfmartin** [comment]
2. This needs more thought and should probably be put into further enhancements
3. This is fixed
4. This needs more thought and should probably be put into further enhancements

The original issue is now fixed. Please raise some enhancement requests if required for the rest which can then be prioritised/planned.
