### ISSUE TITLE
Charts indicate January records when the date precision is correctly Year

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#399]
An example is here: https://records.nbnatlas.org/occurrences/search?taxa=&q=lsid%3ANHMSYS0000544773&fq=assertions%3A%22firstOfYear%22&wkt=&lat=&lon=&radius=&offset=40&max=20#tab_chartsView

These are records that are correctly flagged as Year precision but they appear in the charts as January records.

They also appear as January records in the filter records panel on the left.

**Comment by sophiathirza** [comment]
Just received an email. Adding this to check when fixed:

Nighjar:

https://species.nbnatlas.org/species/NHMSYS0000530242#records [1]

Even Common Swift has a big peak in January - perhaps they do hibernate
in ponds after all!!

https://species.nbnatlas.org/species/NHMSYS0000530165#records [2]

Though less so in the Swallow:

https://species.nbnatlas.org/species/NHMSYS0000530406#records [3]

**Comment by djtfmartin** [comment]
these issues should now be fixed. please verify

**Comment by djtfmartin** [comment]
Theres problems with year ranges still

**Comment by djtfmartin** [comment]
the issues with date ranges should now fixed

**Comment by sophiathirza** [comment]
I still see the problem with year ranges. We still have January records appearing on the charts: https://species.nbnatlas.org/species/NHMSYS0000530242#records

https://records.nbnatlas.org/occurrences/search?q=lsid:NHMSYS0000530242&fq=month:%2201%22#tab_recordsView

**Comment by sophiathirza** [comment]
Could we have reverted because I am sure that I checked the Nightjar and it looked okay.

**Comment by djtfmartin** [comment]
should be fixed (again). Nightjar graph looks ok
